In [23]:
import pandas as pd

# Read the CSV file
df = pd.read_csv('Ecommerce_Purchases.csv')

In [24]:
df

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

In [25]:
# Clean the "Address" column
df['Address'] = df['Address'].str.replace('\n', ' ').str.strip()

In [26]:
df

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448 Alexisborough, NE 771...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508 South John, TN 84...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052 DPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords New Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337 New Cynthia, TX 57826",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,"966 Castaneda Locks West Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785 North Edwardburgh, TX...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343 DPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest Roystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue Grimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

In [27]:
# Group the data by Job and calculate the total purchase amount for each job designation
job_purchase = df.groupby('Job')['Purchase Price'].sum().reset_index()

# Sort the data in descending order based on the total purchase amount
job_purchase_sorted = job_purchase.sort_values('Purchase Price', ascending=False)

# Select the top 5 job designations
top_5_jobs = job_purchase_sorted.head(5)

# Print the relationship between top 5 job designations and total purchase amount
print(top_5_jobs)

                         Job  Purchase Price
158                Dietitian         1605.30
325                   Lawyer         1603.85
473       Purchasing manager         1577.97
589           Therapist, art         1526.31
101  Clinical cytogeneticist         1495.92

In [9]:
# Calculate the mean purchase amount for each job designation
job_mean_purchase = df.groupby('Job')['Purchase Price'].mean().reset_index()

# Sort the data in descending order based on the mean purchase amount
job_mean_purchase_sorted = job_mean_purchase.sort_values('Purchase Price', ascending=False)

# Print the relationship between job designations and mean purchase amount
print(job_mean_purchase_sorted)

                                  Job  Purchase Price
602               Trade mark attorney       73.802727
606                        Translator       70.777647
315                Investment analyst       69.090000
4    Accountant, chartered management       69.082667
149      Designer, industrial/product       68.714667
..                                ...             ...
586             Theatre stage manager       31.580000
170         Editor, magazine features       31.445294
206              Engineer, production       27.771667
48                Art gallery manager       27.381250
352               Marketing executive       26.008889

[623 rows x 2 columns]

In [22]:
#How does purchase value depend on the Internet Browser used and Job (Profession) of the purchaser?
# Extract the browser name from the "Browser Info" column
df['Browser'] = df['Browser Info'].str.split('/').str[0].str.split(' ').str[0]
# Extract the first word from the "Job" column
# df['Job'] = df['Job'].str.split(' ').str[0]

# Group the data by Internet Browser and Job, and calculate the mean purchase value
browser_job_purchase = df.groupby(['Browser', 'Job'])['Purchase Price'].mean().reset_index()

# Sort the data based on the mean purchase value
browser_job_purchase_sorted = browser_job_purchase.sort_values('Purchase Price', ascending=False)

# Print the relationship between Internet Browser, Job, and mean purchase value
print(browser_job_purchase_sorted)

    Browser            Job  Purchase Price
526   Opera         Gaffer          95.755
407   Opera  Archaeologist          95.220
665   Opera        Product          92.665
455   Opera     Conference          92.460
739   Opera   Toxicologist          91.750
..      ...            ...             ...
467   Opera       Customer           9.720
708   Opera           Soil           9.450
448   Opera     Commercial           9.160
431   Opera         Camera           8.360
737   Opera        Tourist           1.105

[759 rows x 3 columns]

In [14]:

# Extract the state from the address and create a new variable "State"
df['State'] = df['Address'].str.split(',').str[-1].str.strip().str.split(' ').str[-2]

# Group the data by State and AM/PM, and calculate the count of purchases
state_time_purchase = df.groupby(['State', 'AM or PM'])['Purchase Price'].count().reset_index()

# Print the patterns of purchases based on State and time of purchase
print(state_time_purchase)

    State AM or PM  Purchase Price
0      AA       AM             165
1      AA       PM             186
2      AE       AM             173
3      AE       PM             158
4      AK       AM              82
..    ...      ...             ...
119    WI       PM              73
120    WV       AM              71
121    WV       PM              86
122    WY       AM              70
123    WY       PM              80

[124 rows x 3 columns]

In [15]:
# Group the data by CC provider and AM/PM, and calculate the mean purchase amount
cc_time_purchase = df.groupby(['CC Provider', 'AM or PM'])['Purchase Price'].mean().reset_index()

# Print the relationship between CC provider, time of purchase, and mean purchase amount
print(cc_time_purchase)

                    CC Provider AM or PM  Purchase Price
0              American Express       AM       50.445631
1              American Express       PM       50.533943
2   Diners Club / Carte Blanche       AM       48.780131
3   Diners Club / Carte Blanche       PM       48.686701
4                      Discover       AM       51.332057
5                      Discover       PM       51.962523
6                  JCB 15 digit       AM       50.613652
7                  JCB 15 digit       PM       51.602405
8                  JCB 16 digit       AM       48.798519
9                  JCB 16 digit       PM       49.815172
10                      Maestro       AM       49.887704
11                      Maestro       PM       50.803524
12                   Mastercard       AM       50.913730
13                   Mastercard       PM       49.291575
14                VISA 13 digit       AM       50.598810
15                VISA 13 digit       PM       52.329869
16                VISA 16 digit       AM       49.357341
17                VISA 16 digit       PM       50.375861
18                      Voyager       AM       53.445537
19                      Voyager       PM       50.401696

In [17]:
# Group the data by Location (State) and calculate the count of purchases
top_5_locations = df['State'].value_counts().head(5)

# Print the top 5 locations for purchases
print(top_5_locations)

AP    376
AA    351
AE    331
IN    183
VI    178
Name: State, dtype: int64